namespace Diariz.Domain.Entities;

/// <summary>A single captured audio recording owned by a user.</summary>
public class Recording
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public ApplicationUser? User { get; set; }

    /// <summary>Auto-generated descriptor (e.g. "Mic 6/26/2026, 1:25 PM"). Shown when
    /// <see cref="Name"/> is unset.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>User-editable display name. Null until set by the user or auto-generated by
    /// the summarisation LLM; the UI falls back to <see cref="Title"/> when null.</summary>
    public string? Name { get; set; }

    /// <summary>Where the audio was captured (microphone vs system/loopback).</summary>
    public RecordingSource Source { get; set; } = RecordingSource.Microphone;

    /// <summary>Object-storage key (MinIO/S3) for the original audio blob.</summary>
    public string BlobKey { get; set; } = string.Empty;

    /// <summary>MIME / container of the stored audio, e.g. audio/webm, audio/wav.</summary>
    public string ContentType { get; set; } = "audio/webm";

    /// <summary>Size in bytes of the stored audio blob (counts toward the owner's storage quota).
    /// Reset to 0 when the audio is deleted (see <see cref="AudioDeletedAt"/>) so it stops counting.</summary>
    public long SizeBytes { get; set; }

    /// <summary>When the user deleted this recording's audio blob to reclaim storage (null = audio
    /// still present). The transcript and metadata are kept; <see cref="HasAudio"/> reflects this.</summary>
    public DateTimeOffset? AudioDeletedAt { get; set; }

    /// <summary>True when the original audio is still available (not deleted). Audio-dependent actions
    /// (playback, download, re-transcribe, re-identify) are only valid when this holds.</summary>
    public bool HasAudio => AudioDeletedAt is null;

    public long DurationMs { get; set; }
    public RecordingStatus Status { get; set; } = RecordingStatus.Uploaded;
    public string? Error { get; set; }

    /// <summary>Optional diarization hints passed to pyannote: force at least/at most this many speakers.
    /// Null = automatic. Used to split two people the diarizer lumped into one (set <see cref="MinSpeakers"/>
    /// = 2). Applied on the next (re-)transcription.</summary>
    public int? MinSpeakers { get; set; }
    public int? MaxSpeakers { get; set; }

    /// <summary>Optional user-defined group; null means "Ungrouped".</summary>
    public Guid? SectionId { get; set; }
    public Section? Section { get; set; }

    /// <summary>Optional meeting type driving the minutes template. Null = the seeded "General Meeting"
    /// default (current behaviour). Persists across re-transcribes. Set to null (SetNull) if the type is deleted.</summary>
    public Guid? MeetingTypeId { get; set; }
    public MeetingType? MeetingType { get; set; }

    /// <summary>Manual sort order within its group (lower = higher in the list). Recordings with the
    /// same position fall back to newest-first by <see cref="CreatedAt"/>.</summary>
    public int Position { get; set; }

    /// <summary>When action items were last extracted for this recording (null = never). Drives the
    /// "show the Actions panel by exception" rule — an extraction that found zero actions still sets it.</summary>
    public DateTimeOffset? ActionsExtractedAt { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>Optional link to the Google Calendar event this recording belongs to (1:1). Null = unlinked.</summary>
    public RecordingCalendarLink? CalendarLink { get; set; }

    public ICollection<Transcription> Transcriptions { get; set; } = new List<Transcription>();
    public ICollection<Speaker> Speakers { get; set; } = new List<Speaker>();
    public ICollection<RecordingAction> Actions { get; set; } = new List<RecordingAction>();
    public ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();
}
