namespace Diariz.Domain.Entities;

/// <summary>A single captured audio recording owned by a user.</summary>
public class Recording
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public ApplicationUser? User { get; set; }

    /// <summary>Auto-generated descriptor (e.g. "Mic 6/26/2026, 1:25 PM"). Shown when
    /// <see cref="Name"/> is unset.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>User-editable display name. Null until set by the user or auto-generated by
    /// the summarisation LLM; the UI falls back to <see cref="Title"/> when null.</summary>
    public string? Name { get; set; }

    /// <summary>Where the audio was captured (microphone vs system/loopback).</summary>
    public RecordingSource Source { get; set; } = RecordingSource.Microphone;

    /// <summary>Object-storage key (MinIO/S3) for the original audio blob.</summary>
    public string BlobKey { get; set; } = string.Empty;

    /// <summary>MIME / container of the stored audio, e.g. audio/webm, audio/wav.</summary>
    public string ContentType { get; set; } = "audio/webm";

    public long DurationMs { get; set; }
    public RecordingStatus Status { get; set; } = RecordingStatus.Uploaded;
    public string? Error { get; set; }

    /// <summary>Optional user-defined group; null means "Ungrouped".</summary>
    public Guid? SectionId { get; set; }
    public Section? Section { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    public ICollection<Transcription> Transcriptions { get; set; } = new List<Transcription>();
    public ICollection<Speaker> Speakers { get; set; } = new List<Speaker>();
}
