import { createHmac, timingSafeEqual } from "node:crypto";

export interface VerifyInput {
  secret: string;
  headers: Record<string, string | string[] | undefined>;
  /// The exact bytes Diariz sent. Never a re-serialised object - the signature covers the original JSON,
  /// and re-serialising it in JavaScript will not reproduce those bytes.
  rawBody: string;
  now?: Date;
  toleranceSeconds?: number;
}

export type VerifyResult = { ok: true } | { ok: false; reason: string };

const DEFAULT_TOLERANCE_SECONDS = 300;

function header(headers: VerifyInput["headers"], name: string): string | undefined {
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() !== name) continue;
    return Array.isArray(value) ? value[0] : value;
  }
  return undefined;
}

function equals(a: string, b: string): boolean {
  const left = Buffer.from(a, "utf8");
  const right = Buffer.from(b, "utf8");
  return left.length === right.length && timingSafeEqual(left, right);
}

/// Standard Webhooks verification: v1,base64(HMAC-SHA256(secret, "<id>.<timestamp>.<body>")).
/// Mirrors src/Diariz.Api/Webhooks/WebhookSigner.cs - the vectors in test/fixtures/signing-vectors.json are
/// generated by that signer, so a change on either side fails one of the two suites.
export function verifyWebhookSignature(input: VerifyInput): VerifyResult {
  if (!input.secret) {
    return { ok: false, reason: "No signing secret is stored for this trigger. Reactivate the workflow." };
  }

  const id = header(input.headers, "webhook-id");
  const timestamp = header(input.headers, "webhook-timestamp");
  const signature = header(input.headers, "webhook-signature");
  if (!id || !timestamp || !signature) {
    return { ok: false, reason: "Missing webhook signature headers." };
  }

  const sent = Number(timestamp);
  if (!Number.isFinite(sent)) {
    return { ok: false, reason: "The webhook timestamp was not a number." };
  }

  const tolerance = input.toleranceSeconds ?? DEFAULT_TOLERANCE_SECONDS;
  const nowSeconds = Math.floor((input.now ?? new Date()).getTime() / 1000);
  if (Math.abs(nowSeconds - sent) > tolerance) {
    return { ok: false, reason: "The webhook timestamp is too old or too far in the future." };
  }

  const expected =
    "v1," + createHmac("sha256", input.secret).update(`${id}.${sent}.${input.rawBody}`).digest("base64");

  // The spec allows several space-delimited signatures so a secret can be rotated without dropping deliveries.
  const matched = signature.split(" ").some((candidate) => equals(candidate.trim(), expected));
  return matched ? { ok: true } : { ok: false, reason: "The webhook signature did not match." };
}
