/**
 * The web app manifest and its icons are shipped as static assets, so - like the Linux PipeWire drop-in
 * next door in linuxSystemAudio.test.ts - the files themselves are the deliverable and these assertions
 * pin the properties they must have to work at all.
 *
 * Chromium surfaces NO error when a site fails the install criteria: the install offer simply never
 * appears. That is why these are asserted rather than eyeballed.
 */
import { readFileSync, existsSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const WEB = join(__dirname, "..", "..");
const ICONS = join(WEB, "public", "icons");
const INDIGO = [79, 70, 229]; // #4f46e5, the mark's background

/// Width and height straight out of the PNG's IHDR chunk: an 8-byte signature, then a 4-byte length and
/// 4-byte type, then width and height as big-endian uint32s. No image library needed.
function pngSize(file: string): { width: number; height: number } {
  const buf = readFileSync(file);
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/// The RGBA of the top-left pixel. Valid only for PNGs written by make-app-icon.js (8-bit RGBA, filter 0
/// on every row), which is all this test reads. Enough to tell a full-bleed icon from one whose corners
/// are transparent, which is the whole difference between the maskable variant and the plain one.
function topLeftPixel(file: string): number[] {
  const buf = readFileSync(file);
  const idat: Buffer[] = [];
  let off = 8;
  while (off < buf.length) {
    const len = buf.readUInt32BE(off);
    if (buf.toString("ascii", off + 4, off + 8) === "IDAT") idat.push(buf.subarray(off + 8, off + 8 + len));
    off += 12 + len;
  }
  const raw = inflateSync(Buffer.concat(idat));
  return [raw[1], raw[2], raw[3], raw[4]]; // raw[0] is the row's filter byte
}

describe("PWA icons", () => {
  it("ships the two sizes Chromium requires, at their real pixel dimensions", () => {
    // A manifest may declare any `sizes` string it likes; Chromium checks the actual image. A 512 entry
    // pointing at a 192 file fails installability with nothing shown to the user.
    for (const px of [192, 512]) {
      const file = join(ICONS, `icon-${px}.png`);
      expect(existsSync(file)).toBe(true);
      expect(pngSize(file)).toEqual({ width: px, height: px });
    }
  });

  it("ships a 512 maskable variant", () => {
    const file = join(ICONS, "icon-maskable-512.png");
    expect(existsSync(file)).toBe(true);
    expect(pngSize(file)).toEqual({ width: 512, height: 512 });
  });

  it("draws the maskable variant full-bleed, not as a copy of the rounded square", () => {
    // The distinction is the entire point of the maskable entry, and a copy would pass every other
    // assertion here. The plain icon's corner is outside the rounded square, so it is transparent; the
    // maskable one must be opaque indigo right into the corner or the platform's mask will shave it.
    expect(topLeftPixel(join(ICONS, "icon-512.png"))[3]).toBe(0);
    expect(topLeftPixel(join(ICONS, "icon-maskable-512.png"))).toEqual([...INDIGO, 255]);
  });

  // Drift guard rather than a behaviour test, in the shape of the build-deb.sh assertion at the end of
  // linuxSystemAudio.test.ts: the committed PNGs are the source of truth, and if the generator is ever
  // repointed elsewhere they would start ageing silently with nothing to catch it.
  it("is generated by the desktop icon generator, so the mark has one definition", () => {
    const script = readFileSync(join(WEB, "..", "desktop", "build", "make-app-icon.js"), "utf8");
    // The exact path.join argument list, not three loose substrings: "web" and "icons" would each match
    // incidental prose in the header comment, so separate checks would keep passing after a repoint.
    expect(script).toContain('"web", "public", "icons"');
    expect(script).toContain("icon-maskable-512.png");
  });
});
