/**
 * The web app manifest and its icons are shipped as static assets, so - like the Linux PipeWire drop-in
 * next door in linuxSystemAudio.test.ts - the files themselves are the deliverable and these assertions
 * pin the properties they must have to work at all.
 *
 * Chromium surfaces NO error when a site fails the install criteria: the install offer simply never
 * appears. That is why these are asserted rather than eyeballed.
 */
import { readFileSync, existsSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const WEB = join(__dirname, "..", "..");
const ICONS = join(WEB, "public", "icons");
const INDIGO = [79, 70, 229]; // #4f46e5, the mark's background

/// Width and height straight out of the PNG's IHDR chunk: an 8-byte signature, then a 4-byte length and
/// 4-byte type, then width and height as big-endian uint32s. No image library needed.
function pngSize(file: string): { width: number; height: number } {
  const buf = readFileSync(file);
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/// The RGBA of the top-left pixel. Valid only for PNGs written by make-app-icon.js (8-bit RGBA, filter 0
/// on every row), which is all this test reads. Enough to tell a full-bleed icon from one whose corners
/// are transparent, which is the whole difference between the maskable variant and the plain one.
function topLeftPixel(file: string): number[] {
  const buf = readFileSync(file);
  const idat: Buffer[] = [];
  let off = 8;
  while (off < buf.length) {
    const len = buf.readUInt32BE(off);
    if (buf.toString("ascii", off + 4, off + 8) === "IDAT") idat.push(buf.subarray(off + 8, off + 8 + len));
    off += 12 + len;
  }
  const raw = inflateSync(Buffer.concat(idat));
  return [raw[1], raw[2], raw[3], raw[4]]; // raw[0] is the row's filter byte
}

describe("PWA icons", () => {
  it("ships the two sizes Chromium requires, at their real pixel dimensions", () => {
    // A manifest may declare any `sizes` string it likes; Chromium checks the actual image. A 512 entry
    // pointing at a 192 file fails installability with nothing shown to the user.
    for (const px of [192, 512]) {
      const file = join(ICONS, `icon-${px}.png`);
      expect(existsSync(file)).toBe(true);
      expect(pngSize(file)).toEqual({ width: px, height: px });
    }
  });

  it("ships a 512 maskable variant", () => {
    const file = join(ICONS, "icon-maskable-512.png");
    expect(existsSync(file)).toBe(true);
    expect(pngSize(file)).toEqual({ width: 512, height: 512 });
  });

  it("draws the maskable variant full-bleed, not as a copy of the rounded square", () => {
    // The distinction is the entire point of the maskable entry, and a copy would pass every other
    // assertion here. The plain icon's corner is outside the rounded square, so it is transparent; the
    // maskable one must be opaque indigo right into the corner or the platform's mask will shave it.
    expect(topLeftPixel(join(ICONS, "icon-512.png"))[3]).toBe(0);
    expect(topLeftPixel(join(ICONS, "icon-maskable-512.png"))).toEqual([...INDIGO, 255]);
  });

  // Drift guard rather than a behaviour test, in the shape of the build-deb.sh assertion at the end of
  // linuxSystemAudio.test.ts: the committed PNGs are the source of truth, and if the generator is ever
  // repointed elsewhere they would start ageing silently with nothing to catch it.
  it("is generated by the desktop icon generator, so the mark has one definition", () => {
    const script = readFileSync(join(WEB, "..", "desktop", "build", "make-app-icon.js"), "utf8");
    // The exact path.join argument list, not three loose substrings: "web" and "icons" would each match
    // incidental prose in the header comment, so separate checks would keep passing after a repoint.
    expect(script).toContain('"web", "public", "icons"');
    expect(script).toContain("icon-maskable-512.png");
  });
});

describe("web app manifest", () => {
  const MANIFEST = join(WEB, "public", "manifest.webmanifest");
  const manifest = () => JSON.parse(readFileSync(MANIFEST, "utf8"));

  it("is shipped as a static asset the app can serve", () => {
    expect(existsSync(MANIFEST)).toBe(true);
  });

  // Each of the next four is a hard Chromium install requirement. Missing any one of them means the
  // install offer never appears, with no error anywhere for the user or the developer to see.
  it("names the app", () => {
    expect(manifest().name).toBe("Diariz");
    expect(manifest().short_name).toBe("Diariz");
  });

  it("starts at the app root", () => {
    expect(manifest().start_url).toBe("/");
  });

  it("opens without browser chrome", () => {
    expect(manifest().display).toBe("standalone");
  });

  it("does not defer to a related native app", () => {
    // `prefer_related_applications: true` would make Chromium point at a store listing instead of
    // installing the site. Absent counts as false, which is what we want, so assert it never appears.
    expect(manifest().prefer_related_applications).toBeUndefined();
  });

  it("declares icons that exist at the sizes it claims", () => {
    // The size strings are what Chromium checks against the real files, so this is the assertion that
    // catches a typo'd path or a renamed icon.
    for (const icon of manifest().icons) {
      const file = join(WEB, "public", icon.src.replace(/^\//, ""));
      expect(existsSync(file)).toBe(true);
      const [w, h] = icon.sizes.split("x").map(Number);
      expect(pngSize(file)).toEqual({ width: w, height: h });
      expect(icon.type).toBe("image/png");
    }
  });

  it("declares both required sizes and a maskable variant", () => {
    const icons = manifest().icons as { sizes: string; purpose?: string }[];
    expect(icons.map((i) => i.sizes)).toContain("192x192");
    expect(icons.map((i) => i.sizes)).toContain("512x512");
    expect(icons.some((i) => i.purpose === "maskable")).toBe(true);
  });

  it("tints the installed window with the brand indigo", () => {
    // A single static value cannot follow the app's light/dark theme, so it is deliberately the brand
    // colour: intentional in both, rather than a light bar above a dark app. See the spec.
    expect(manifest().theme_color).toBe("#4f46e5");
    expect(manifest().background_color).toBe("#4f46e5");
  });

  it("carries no version number, which would only drift", () => {
    expect(manifest().version).toBeUndefined();
  });

  it("is linked from the document, without which it is inert", () => {
    const html = readFileSync(join(WEB, "index.html"), "utf8");
    expect(html).toContain('rel="manifest"');
    expect(html).toContain("/manifest.webmanifest");
  });
});

describe("nginx serves the manifest correctly", () => {
  const conf = () => readFileSync(join(WEB, "nginx.conf"), "utf8");

  it("gives the manifest its MIME type, which the base image does not know", () => {
    // nginx:alpine's default mime.types has no `manifest` entry at all (verified on 1.31.2), so the
    // extension is undetermined and `default_type` is what governs it. Vite's dev server resolves
    // .webmanifest on its own, so getting this wrong only ever shows up on a deployed box.
    expect(conf()).toMatch(/location = \/manifest\.webmanifest \{[^}]*default_type application\/manifest\+json;/);
  });

  it("never declares a `types` block, which would replace the whole inherited map", () => {
    // Regression guard for a real bug caught only by curling the running container: a `types { ... }`
    // block does NOT extend nginx's MIME table, it REPLACES it. Adding one to map .webmanifest turned
    // index.html, the JS bundle and every PNG into application/octet-stream - a completely broken app -
    // and `nginx -t` reported the config as valid. Use `default_type` in a location instead.
    expect(conf()).not.toMatch(/^\s*types\s*\{/m);
  });

  it("revalidates the manifest, which names the icons", () => {
    // Same argument the index.html block in that file makes at length: a document that names other
    // assets must not be served from a heuristic cache, or a stale copy pins the app's identity.
    expect(conf()).toMatch(/location = \/manifest\.webmanifest \{[^}]*no-cache/);
  });

  it("caches the icons hard, since the mark is stable", () => {
    expect(conf()).toMatch(/location \/icons\/ \{[^}]*immutable/);
  });
});
